lima-mali450-test:arm64:
  parallel: 4
  extends:
    - .lava-test:arm64
    - .lima-rules
  variables:
    DEVICE_TYPE: meson-gxl-s805x-libretech-ac
    DTB: ${DEVICE_TYPE}
    GPU_VERSION: lima
    DEQP_PARALLEL: 2
    DEQP_EXPECTED_RENDERER: Mali450

  tags:
    - mesa-ci-aarch64-lava-lima
