enum lima_query_groups {
    lima_vertex_processor_group,
    lima_fragment_processor_group,
    lima_l2_group,
    lima_l2_1_group,
    lima_l2_2_group,
    lima_query_groups_num,
};
enum lima_queries {
    lima_gp_active_cycles,
    lima_gp_active_cycles_vertex_shader,
    lima_gp_active_cycles_vertex_storer,
    lima_gp_active_cycles_vertex_loader,
    lima_gp_cycles_vertex_loader_waiting_for_vertex_shader,
    lima_gp_words_read_system_bus,
    lima_gp_words_written_system_bus,
    lima_gp_read_bursts_system_bus,
    lima_gp_write_bursts_system_bus,
    lima_gp_vertices_processed,
    lima_gp_vertices_fetched,
    lima_gp_primitives_fetched,
    lima_gp_primitives_culled,
    lima_gp_commands_written_to_tiles,
    lima_gp_memory_blocks_allocated,
    lima_gp_vertex_loader_cache_misses,
    lima_gp_active_cycles_vertex_shader_command_processor,
    lima_gp_active_cycles_plbu_command_processor,
    lima_gp_active_cycles_plbu_list_writer,
    lima_gp_active_cycles_plbu_geometry_processing,
    lima_gp_active_cycles_plbu_primitive_assembly,
    lima_gp_active_cycles_plbu_vertex_fetcher,
    lima_gp_active_cycles_bounding_box_and_command_generator,
    lima_gp_active_cycles_scissor_tile_iterator,
    lima_gp_active_cycles_plbu_tile_iterator,
    lima_pp_active_clock_cycles,
    lima_pp_total_bus_reads,
    lima_pp_total_bus_writes,
    lima_pp_bus_read_request_cycles,
    lima_pp_bus_write_request_cycles,
    lima_pp_bus_read_transactions_count,
    lima_pp_bus_write_transactions,
    lima_pp_tile_writeback_writes,
    lima_pp_store_unit_writes,
    lima_pp_texture_cache_uncompressed_reads,
    lima_pp_polygon_list_reads,
    lima_pp_rsw_reads,
    lima_pp_vertex_cache_reads,
    lima_pp_uniform_remapping_reads,
    lima_pp_program_cache_reads,
    lima_pp_varying_reads,
    lima_pp_texture_descriptors_reads,
    lima_pp_texture_descriptor_remapping_reads,
    lima_pp_load_unit_reads,
    lima_pp_polygon_count,
    lima_pp_pixel_rectangle_count,
    lima_pp_lines_count,
    lima_pp_points_count,
    lima_pp_stall_cycles_polygonlistreader,
    lima_pp_stall_cycles_triangle_setup,
    lima_pp_quad_rasterized_count,
    lima_pp_fragment_rasterized_count,
    lima_pp_fragment_rejected_fragment_kill_count,
    lima_pp_fragment_rejected_fwd_fragment_kill_count,
    lima_pp_fragment_passed_z_stencil_count,
    lima_pp_patches_rejected_early_z_stencil_count,
    lima_pp_patches_evaluated,
    lima_pp_instruction_completed_count,
    lima_pp_instruction_failed_rendezvous_count,
    lima_pp_instruction_failed_varying_miss_count,
    lima_pp_instruction_failed_texture_miss_count,
    lima_pp_instruction_failed_load_miss_count,
    lima_pp_instruction_failed_tile_read_miss_count,
    lima_pp_instruction_failed_store_miss_count,
    lima_pp_rendezvous_breakage_count,
    lima_pp_pipeline_bubbles_cycle_count,
    lima_pp_texture_mapper_multipass_count,
    lima_pp_texture_mapper_cycle_count,
    lima_pp_vertex_cache_hit_count,
    lima_pp_vertex_cache_miss_count,
    lima_pp_varying_cache_hit_count,
    lima_pp_varying_cache_miss_count,
    lima_pp_varying_cache_conflict_miss_count,
    lima_pp_texture_cache_hit_count,
    lima_pp_texture_cache_miss_count,
    lima_pp_texture_cache_conflict_miss_count,
    lima_pp_compressed_texture_cache_hit_count,
    lima_pp_compressed_texture_cache_miss_count,
    lima_pp_load_store_cache_hit_count,
    lima_pp_load_store_cache_miss_count,
    lima_pp_program_cache_hit_count,
    lima_pp_program_cache_miss_count,
    lima_l2_cache_read_transactions_master,
    lima_l2_cache_read_transactions_all_slaves,
    lima_l2_cache_read_transactions_slave_0,
    lima_l2_cache_read_transactions_slave_1,
    lima_l2_cache_read_transactions_slave_2,
    lima_l2_cache_read_transactions_slave_3,
    lima_l2_cache_read_transactions_slave_4,
    lima_l2_cache_total_clock_cycles,
    lima_l2_cache_write_transactions_master,
    lima_l2_cache_write_transactions_all_slaves,
    lima_l2_cache_write_transactions_slave_0,
    lima_l2_cache_write_transactions_slave_1,
    lima_l2_cache_write_transactions_slave_2,
    lima_l2_cache_write_transactions_slave_3,
    lima_l2_cache_write_transactions_slave_4,
    lima_l2_cache_active_clock_cycles,
    lima_l2_cache_words_read_master,
    lima_l2_cache_words_read_all_slaves,
    lima_l2_cache_words_read_slave_0,
    lima_l2_cache_words_read_slave_1,
    lima_l2_cache_words_read_slave_2,
    lima_l2_cache_words_read_slave_3,
    lima_l2_cache_words_read_slave_4,
    lima_l2_cache_words_written_master,
    lima_l2_cache_words_written_all_slaves,
    lima_l2_cache_words_written_slave_0,
    lima_l2_cache_words_written_slave_1,
    lima_l2_cache_words_written_slave_2,
    lima_l2_cache_words_written_slave_3,
    lima_l2_cache_words_written_slave_4,
    lima_l2_cache_read_hits,
    lima_l2_cache_read_misses,
    lima_l2_cache_write_invalidates,
    lima_l2_cache_read_invalidates,
    lima_l2_cache_cacheable_read_transactions,
    lima_l2_cache_1_read_transactions_master,
    lima_l2_cache_1_read_transactions_all_slaves,
    lima_l2_cache_1_read_transactions_slave_0,
    lima_l2_cache_1_read_transactions_slave_1,
    lima_l2_cache_1_read_transactions_slave_2,
    lima_l2_cache_1_read_transactions_slave_3,
    lima_l2_cache_1_read_transactions_slave_4,
    lima_l2_cache_1_total_clock_cycles,
    lima_l2_cache_1_write_transactions_master,
    lima_l2_cache_1_write_transactions_all_slaves,
    lima_l2_cache_1_write_transactions_slave_0,
    lima_l2_cache_1_write_transactions_slave_1,
    lima_l2_cache_1_write_transactions_slave_2,
    lima_l2_cache_1_write_transactions_slave_3,
    lima_l2_cache_1_write_transactions_slave_4,
    lima_l2_cache_1_active_clock_cycles,
    lima_l2_cache_1_words_read_master,
    lima_l2_cache_1_words_read_all_slaves,
    lima_l2_cache_1_words_read_slave_0,
    lima_l2_cache_1_words_read_slave_1,
    lima_l2_cache_1_words_read_slave_2,
    lima_l2_cache_1_words_read_slave_3,
    lima_l2_cache_1_words_read_slave_4,
    lima_l2_cache_1_words_written_master,
    lima_l2_cache_1_words_written_all_slaves,
    lima_l2_cache_1_words_written_slave_0,
    lima_l2_cache_1_words_written_slave_1,
    lima_l2_cache_1_words_written_slave_2,
    lima_l2_cache_1_words_written_slave_3,
    lima_l2_cache_1_words_written_slave_4,
    lima_l2_cache_1_read_hits,
    lima_l2_cache_1_read_misses,
    lima_l2_cache_1_write_invalidates,
    lima_l2_cache_1_read_invalidates,
    lima_l2_cache_1_cacheable_read_transactions,
    lima_l2_cache_2_read_transactions_master,
    lima_l2_cache_2_read_transactions_all_slaves,
    lima_l2_cache_2_read_transactions_slave_0,
    lima_l2_cache_2_read_transactions_slave_1,
    lima_l2_cache_2_read_transactions_slave_2,
    lima_l2_cache_2_read_transactions_slave_3,
    lima_l2_cache_2_read_transactions_slave_4,
    lima_l2_cache_2_total_clock_cycles,
    lima_l2_cache_2_write_transactions_master,
    lima_l2_cache_2_write_transactions_all_slaves,
    lima_l2_cache_2_write_transactions_slave_0,
    lima_l2_cache_2_write_transactions_slave_1,
    lima_l2_cache_2_write_transactions_slave_2,
    lima_l2_cache_2_write_transactions_slave_3,
    lima_l2_cache_2_write_transactions_slave_4,
    lima_l2_cache_2_active_clock_cycles,
    lima_l2_cache_2_words_read_master,
    lima_l2_cache_2_words_read_all_slaves,
    lima_l2_cache_2_words_read_slave_0,
    lima_l2_cache_2_words_read_slave_1,
    lima_l2_cache_2_words_read_slave_2,
    lima_l2_cache_2_words_read_slave_3,
    lima_l2_cache_2_words_read_slave_4,
    lima_l2_cache_2_words_written_master,
    lima_l2_cache_2_words_written_all_slaves,
    lima_l2_cache_2_words_written_slave_0,
    lima_l2_cache_2_words_written_slave_1,
    lima_l2_cache_2_words_written_slave_2,
    lima_l2_cache_2_words_written_slave_3,
    lima_l2_cache_2_words_written_slave_4,
    lima_l2_cache_2_read_hits,
    lima_l2_cache_2_read_misses,
    lima_l2_cache_2_write_invalidates,
    lima_l2_cache_2_read_invalidates,
    lima_l2_cache_2_cacheable_read_transactions,
    lima_queries_num,
};
const static struct group_data {
    const char* name;
    unsigned max_active_queries;
    unsigned num_queries;
} lima_group_data[] = {
    [lima_vertex_processor_group] = {
        .name = "lima_vertex_processor",
        .max_active_queries = 2,
        .num_queries = 25,
    },
    [lima_fragment_processor_group] = {
        .name = "lima_fragment_processor",
        .max_active_queries = 2,
        .num_queries = 57,
    },
    [lima_l2_group] = {
        .name = "lima_l2",
        .max_active_queries = 2,
        .num_queries = 35,
    },
    [lima_l2_1_group] = {
        .name = "lima_l2_1",
        .max_active_queries = 2,
        .num_queries = 35,
    },
    [lima_l2_2_group] = {
        .name = "lima_l2_2",
        .max_active_queries = 2,
        .num_queries = 35,
    },
};
const static struct query_data {
    const char* name;
    const char* desc;
    int group_id;
    int event;
    int event_delta;
} lima_query_data[] = {
    [lima_gp_active_cycles]
    = {
        .name = "lima_gp_active_cycles",
        .desc = "Mali-4xx VP: Number of cycles per frame the MaliGP2 was active.",
        .group_id = lima_vertex_processor_group,
        .event = 0x01,
    },
    [lima_gp_active_cycles_vertex_shader] = {
        .name = "lima_gp_active_cycles_vertex_shader",
        .desc = "Mali-4xx VP: Number of cycles per frame the vertex shader unit was active.",
        .group_id = lima_vertex_processor_group,
        .event = 0x02,
    },
    [lima_gp_active_cycles_vertex_storer] = {
        .name = "lima_gp_active_cycles_vertex_storer",
        .desc = "Mali-4xx VP: Number of cycles per frame the vertex storer unit was active.",
        .group_id = lima_vertex_processor_group,
        .event = 0x03,
    },
    [lima_gp_active_cycles_vertex_loader] = {
        .name = "lima_gp_active_cycles_vertex_loader",
        .desc = "Mali-4xx VP: Number of cycles per frame the vertex loader unit was active.",
        .group_id = lima_vertex_processor_group,
        .event = 0x04,
    },
    [lima_gp_cycles_vertex_loader_waiting_for_vertex_shader] = {
        .name = "lima_gp_cycles_vertex_loader_waiting_for_vertex_shader",
        .desc = "Mali-4xx VP: Number of cycles per frame the vertex loader was idle while waiting on the vertex shader.",
        .group_id = lima_vertex_processor_group,
        .event = 0x05,
    },
    [lima_gp_words_read_system_bus] = {
        .name = "lima_gp_words_read_system_bus",
        .desc = "Mali-4xx VP: Total number of 64 bit words read by the GP2 from the system bus per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x06,
    },
    [lima_gp_words_written_system_bus] = {
        .name = "lima_gp_words_written_system_bus",
        .desc = "Mali-4xx VP: Total number of 64 bit words written by the GP2 to the system bus per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x07,
    },
    [lima_gp_read_bursts_system_bus] = {
        .name = "lima_gp_read_bursts_system_bus",
        .desc = "Mali-4xx VP: Number of read bursts by the GP2 from the system bus per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x08,
    },
    [lima_gp_write_bursts_system_bus] = {
        .name = "lima_gp_write_bursts_system_bus",
        .desc = "Mali-4xx VP: Number of write bursts from the MaliGP2 to the system bus per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x09,
    },
    [lima_gp_vertices_processed] = {
        .name = "lima_gp_vertices_processed",
        .desc = "Mali-4xx VP: Number of vertices processed by the MaliGP2 per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x0a,
    },
    [lima_gp_vertices_fetched] = {
        .name = "lima_gp_vertices_fetched",
        .desc = "Mali-4xx VP: Number of vertices fetched by the MaliGP2 per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x0b,
    },
    [lima_gp_primitives_fetched] = {
        .name = "lima_gp_primitives_fetched",
        .desc = "Mali-4xx VP: Number of graphics primitives fetched by the MaliGP2 per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x0c,
    },
    [lima_gp_primitives_culled] = {
        .name = "lima_gp_primitives_culled",
        .desc = "Mali-4xx VP: Number of graphics primitives discarded per frame, because they were seen from the back or were offscreen.",
        .group_id = lima_vertex_processor_group,
        .event = 0x0e,
    },
    [lima_gp_commands_written_to_tiles] = {
        .name = "lima_gp_commands_written_to_tiles",
        .desc = "Mali-4xx VP: Number of commands (8 Bytes, mainly primitives) written by GP2 to the PP input data structure per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x0f,
    },
    [lima_gp_memory_blocks_allocated] = {
        .name = "lima_gp_memory_blocks_allocated",
        .desc = "Mali-4xx VP: Number of overflow data blocks needed for outputting the PP input data structure per frame .",
        .group_id = lima_vertex_processor_group,
        .event = 0x10,
    },
    [lima_gp_vertex_loader_cache_misses] = {
        .name = "lima_gp_vertex_loader_cache_misses",
        .desc = "Mali-4xx VP: Number of cache misses for the vertex shader's vertex input unit per frame.",
        .group_id = lima_vertex_processor_group,
        .event = 0x13,
    },
    [lima_gp_active_cycles_vertex_shader_command_processor] = {
        .name = "lima_gp_active_cycles_vertex_shader_command_processor",
        .desc = "Mali-4xx VP: Number of cycles per frame the GP2 vertex shader command processor was active. This includes time waiting for semaphores.",
        .group_id = lima_vertex_processor_group,
        .event = 0x16,
    },
    [lima_gp_active_cycles_plbu_command_processor] = {
        .name = "lima_gp_active_cycles_plbu_command_processor",
        .desc = "Mali-4xx VP: Number of cycles per frame the MaliGP2 PLBU command processor was active. This includes time waiting for semaphores.",
        .group_id = lima_vertex_processor_group,
        .event = 0x17,
    },
    [lima_gp_active_cycles_plbu_list_writer] = {
        .name = "lima_gp_active_cycles_plbu_list_writer",
        .desc = "Mali-4xx VP: Number of cycles per frame the MaliGP2 PLBU output unit was active. This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x18,
    },
    [lima_gp_active_cycles_plbu_geometry_processing] = {
        .name = "lima_gp_active_cycles_plbu_geometry_processing",
        .desc = "Mali-4xx VP: Number of cycles per frame the MaliGP2 PLBU was active, excepting final data output. In other words: active cycles through the prepare list commands. This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x19,
    },
    [lima_gp_active_cycles_plbu_primitive_assembly] = {
        .name = "lima_gp_active_cycles_plbu_primitive_assembly",
        .desc = "Mali-4xx VP: Number of active cycles per frame spent by the MaliGP2 PLBU doing primitive assembly. This does not include scissoring or final output. This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x1b,
    },
    [lima_gp_active_cycles_plbu_vertex_fetcher] = {
        .name = "lima_gp_active_cycles_plbu_vertex_fetcher",
        .desc = "Mali-4xx VP: Number of active cycles per frame spent by the MaliGP2 PLBU fetching vertex data. This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x1c,
    },
    [lima_gp_active_cycles_bounding_box_and_command_generator] = {
        .name = "lima_gp_active_cycles_bounding_box_and_command_generator",
        .desc = "Mali-4xx VP: Number of active cycles per frame spent by the MaliGP2 PLBU setting up bounding boxes and commands (mainly graphics primitives). This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x1e,
    },
    [lima_gp_active_cycles_scissor_tile_iterator] = {
        .name = "lima_gp_active_cycles_scissor_tile_iterator",
        .desc = "Mali-4xx VP: Number of active cycles per frame spent by the MaliGP2 PLBU iterating over tiles to perform scissoring. This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x20,
    },
    [lima_gp_active_cycles_plbu_tile_iterator] = {
        .name = "lima_gp_active_cycles_plbu_tile_iterator",
        .desc = "Mali-4xx VP: Number of active cycles per frame spent by the MaliGP2 PLBU iterating over the tiles in the bounding box generating commands (mainly graphics primitives). This includes time spent waiting on the bus.",
        .group_id = lima_vertex_processor_group,
        .event = 0x21,
    },
    [lima_pp_active_clock_cycles] = {
        .name = "lima_pp_active_clock_cycles",
        .desc = "Mali-4xx FP: Active clock cycles, between polygon start and IRQ.",
        .group_id = lima_fragment_processor_group,
        .event = 0x00,
    },
    [lima_pp_total_bus_reads] = {
        .name = "lima_pp_total_bus_reads",
        .desc = "Mali-4xx FP: Total number of 64-bit words read from the bus.",
        .group_id = lima_fragment_processor_group,
        .event = 0x02,
    },
    [lima_pp_total_bus_writes] = {
        .name = "lima_pp_total_bus_writes",
        .desc = "Mali-4xx FP: Total number of 64-bit words written to the bus.",
        .group_id = lima_fragment_processor_group,
        .event = 0x03,
    },
    [lima_pp_bus_read_request_cycles] = {
        .name = "lima_pp_bus_read_request_cycles",
        .desc = "Mali-4xx FP: Number of cycles during which the bus read request signal was HIGH.",
        .group_id = lima_fragment_processor_group,
        .event = 0x04,
    },
    [lima_pp_bus_write_request_cycles] = {
        .name = "lima_pp_bus_write_request_cycles",
        .desc = "Mali-4xx FP: Number of cycles during which the bus write request signal was HIGH.",
        .group_id = lima_fragment_processor_group,
        .event = 0x05,
    },
    [lima_pp_bus_read_transactions_count] = {
        .name = "lima_pp_bus_read_transactions_count",
        .desc = "Mali-4xx FP: Number of read requests accepted by the bus.",
        .group_id = lima_fragment_processor_group,
        .event = 0x06,
    },
    [lima_pp_bus_write_transactions] = {
        .name = "lima_pp_bus_write_transactions",
        .desc = "Mali-4xx FP: Number of write requests accepted by the bus.",
        .group_id = lima_fragment_processor_group,
        .event = 0x07,
    },
    [lima_pp_tile_writeback_writes] = {
        .name = "lima_pp_tile_writeback_writes",
        .desc = "Mali-4xx FP: 64-bit words written to the bus by the writeback unit.",
        .group_id = lima_fragment_processor_group,
        .event = 0x09,
    },
    [lima_pp_store_unit_writes] = {
        .name = "lima_pp_store_unit_writes",
        .desc = "Mali-4xx FP: 64-bit words written to the bus by the store unit.",
        .group_id = lima_fragment_processor_group,
        .event = 0x0a,
    },
    [lima_pp_texture_cache_uncompressed_reads] = {
        .name = "lima_pp_texture_cache_uncompressed_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus into the uncompressed textures cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x0d,
    },
    [lima_pp_polygon_list_reads] = {
        .name = "lima_pp_polygon_list_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus by the polygon list reader.",
        .group_id = lima_fragment_processor_group,
        .event = 0x0e,
    },
    [lima_pp_rsw_reads] = {
        .name = "lima_pp_rsw_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus into the Render State Word register.",
        .group_id = lima_fragment_processor_group,
        .event = 0x0f,
    },
    [lima_pp_vertex_cache_reads] = {
        .name = "lima_pp_vertex_cache_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus into the vertex cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x10,
    },
    [lima_pp_uniform_remapping_reads] = {
        .name = "lima_pp_uniform_remapping_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus when reading from the uniform remapping table.",
        .group_id = lima_fragment_processor_group,
        .event = 0x11,
    },
    [lima_pp_program_cache_reads] = {
        .name = "lima_pp_program_cache_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus into the fragment shader program cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x12,
    },
    [lima_pp_varying_reads] = {
        .name = "lima_pp_varying_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words containing varyings generated by the vertex processing read from the bus.",
        .group_id = lima_fragment_processor_group,
        .event = 0x13,
    },
    [lima_pp_texture_descriptors_reads] = {
        .name = "lima_pp_texture_descriptors_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words containing texture descriptors read from the bus.",
        .group_id = lima_fragment_processor_group,
        .event = 0x14,
    },
    [lima_pp_texture_descriptor_remapping_reads] = {
        .name = "lima_pp_texture_descriptor_remapping_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus when reading from the texture descriptor remapping table.",
        .group_id = lima_fragment_processor_group,
        .event = 0x15,
    },
    [lima_pp_load_unit_reads] = {
        .name = "lima_pp_load_unit_reads",
        .desc = "Mali-4xx FP: Number of 64-bit words read from the bus by the LOAD sub-instruction.",
        .group_id = lima_fragment_processor_group,
        .event = 0x17,
    },
    [lima_pp_polygon_count] = {
        .name = "lima_pp_polygon_count",
        .desc = "Mali-4xx FP: Number of triangles read from the polygon list.",
        .group_id = lima_fragment_processor_group,
        .event = 0x18,
    },
    [lima_pp_pixel_rectangle_count] = {
        .name = "lima_pp_pixel_rectangle_count",
        .desc = "Mali-4xx FP: Number of pixel rectangles read from the polygon list.",
        .group_id = lima_fragment_processor_group,
        .event = 0x19,
    },
    [lima_pp_lines_count] = {
        .name = "lima_pp_lines_count",
        .desc = "Mali-4xx FP: Number of lines read from the polygon list.",
        .group_id = lima_fragment_processor_group,
        .event = 0x1a,
    },
    [lima_pp_points_count] = {
        .name = "lima_pp_points_count",
        .desc = "Mali-4xx FP: Number of points read from the polygon list.",
        .group_id = lima_fragment_processor_group,
        .event = 0x1b,
    },
    [lima_pp_stall_cycles_polygonlistreader] = {
        .name = "lima_pp_stall_cycles_polygonlistreader",
        .desc = "Mali-4xx FP: Number of clock cycles the Polygon List Reader waited for output being collected.",
        .group_id = lima_fragment_processor_group,
        .event = 0x1c,
    },
    [lima_pp_stall_cycles_triangle_setup] = {
        .name = "lima_pp_stall_cycles_triangle_setup",
        .desc = "Mali-4xx FP: Number of clock cycles the TSC waited for input.",
        .group_id = lima_fragment_processor_group,
        .event = 0x1d,
    },
    [lima_pp_quad_rasterized_count] = {
        .name = "lima_pp_quad_rasterized_count",
        .desc = "Mali-4xx FP: Number of 2x?2 quads output from rasterizer.",
        .group_id = lima_fragment_processor_group,
        .event = 0x1e,
    },
    [lima_pp_fragment_rasterized_count] = {
        .name = "lima_pp_fragment_rasterized_count",
        .desc = "Mali-4xx FP: Number of fragment rasterized. Fragments/(Quads*4) gives average actual fragments per quad.",
        .group_id = lima_fragment_processor_group,
        .event = 0x1f,
    },
    [lima_pp_fragment_rejected_fragment_kill_count] = {
        .name = "lima_pp_fragment_rejected_fragment_kill_count",
        .desc = "Mali-4xx FP: Number of fragments exiting the fragment shader as killed.",
        .group_id = lima_fragment_processor_group,
        .event = 0x20,
    },
    [lima_pp_fragment_rejected_fwd_fragment_kill_count] = {
        .name = "lima_pp_fragment_rejected_fwd_fragment_kill_count",
        .desc = "Mali-4xx FP: Number of fragments killed by forward fragment kill.",
        .group_id = lima_fragment_processor_group,
        .event = 0x21,
    },
    [lima_pp_fragment_passed_z_stencil_count] = {
        .name = "lima_pp_fragment_passed_z_stencil_count",
        .desc = "Mali-4xx FP: Number of fragments passing Z and stencil test.",
        .group_id = lima_fragment_processor_group,
        .event = 0x22,
    },
    [lima_pp_patches_rejected_early_z_stencil_count] = {
        .name = "lima_pp_patches_rejected_early_z_stencil_count",
        .desc = "Mali-4xx FP: Number of patches rejected by EarlyZ. A patch can be 8x8, 4x4 or 2x2 pixels.",
        .group_id = lima_fragment_processor_group,
        .event = 0x23,
    },
    [lima_pp_patches_evaluated] = {
        .name = "lima_pp_patches_evaluated",
        .desc = "Mali-4xx FP: Number of patches evaluated for EarlyZ rejection.",
        .group_id = lima_fragment_processor_group,
        .event = 0x24,
    },
    [lima_pp_instruction_completed_count] = {
        .name = "lima_pp_instruction_completed_count",
        .desc = "Mali-4xx FP: Number of fragment shader instruction words completed. It is a function of pixels processed and the length of the shader programs.",
        .group_id = lima_fragment_processor_group,
        .event = 0x25,
    },
    [lima_pp_instruction_failed_rendezvous_count] = {
        .name = "lima_pp_instruction_failed_rendezvous_count",
        .desc = "Mali-4xx FP: Number of fragment shader instructions not completed because of failed Rendezvous.",
        .group_id = lima_fragment_processor_group,
        .event = 0x26,
    },
    [lima_pp_instruction_failed_varying_miss_count] = {
        .name = "lima_pp_instruction_failed_varying_miss_count",
        .desc = "Mali-4xx FP: Number of fragment shader instructions not completed because of failed varying operation.",
        .group_id = lima_fragment_processor_group,
        .event = 0x27,
    },
    [lima_pp_instruction_failed_texture_miss_count] = {
        .name = "lima_pp_instruction_failed_texture_miss_count",
        .desc = "Mali-4xx FP: Number of fragment shader instructions not completed because of failed texture operation.",
        .group_id = lima_fragment_processor_group,
        .event = 0x28,
    },
    [lima_pp_instruction_failed_load_miss_count] = {
        .name = "lima_pp_instruction_failed_load_miss_count",
        .desc = "Mali-4xx FP: Number of fragment shader instructions not completed because of failed load operation.",
        .group_id = lima_fragment_processor_group,
        .event = 0x29,
    },
    [lima_pp_instruction_failed_tile_read_miss_count] = {
        .name = "lima_pp_instruction_failed_tile_read_miss_count",
        .desc = "Mali-4xx FP: Number of fragment shader instructions not completed because of failed read from the tilebuffer.",
        .group_id = lima_fragment_processor_group,
        .event = 0x2a,
    },
    [lima_pp_instruction_failed_store_miss_count] = {
        .name = "lima_pp_instruction_failed_store_miss_count",
        .desc = "Mali-4xx FP: Number of fragment shader instructions not completed because of failed store operation.",
        .group_id = lima_fragment_processor_group,
        .event = 0x2b,
    },
    [lima_pp_rendezvous_breakage_count] = {
        .name = "lima_pp_rendezvous_breakage_count",
        .desc = "Mali-4xx FP: Number of Rendezvous breakages reported.",
        .group_id = lima_fragment_processor_group,
        .event = 0x2c,
    },
    [lima_pp_pipeline_bubbles_cycle_count] = {
        .name = "lima_pp_pipeline_bubbles_cycle_count",
        .desc = "Mali-4xx FP: Number of unused cycles in the fragment shader while rendering is active.",
        .group_id = lima_fragment_processor_group,
        .event = 0x2d,
    },
    [lima_pp_texture_mapper_multipass_count] = {
        .name = "lima_pp_texture_mapper_multipass_count",
        .desc = "Mali-4xx FP: Number of texture operations looped because of more texture passes needed.",
        .group_id = lima_fragment_processor_group,
        .event = 0x2e,
    },
    [lima_pp_texture_mapper_cycle_count] = {
        .name = "lima_pp_texture_mapper_cycle_count",
        .desc = "Mali-4xx FP: Number of texture operation cycles.",
        .group_id = lima_fragment_processor_group,
        .event = 0x2f,
    },
    [lima_pp_vertex_cache_hit_count] = {
        .name = "lima_pp_vertex_cache_hit_count",
        .desc = "Mali-4xx FP: Number of times a requested vertex was found in the cache (Number of vertex cache hits).",
        .group_id = lima_fragment_processor_group,
        .event = 0x30,
    },
    [lima_pp_vertex_cache_miss_count] = {
        .name = "lima_pp_vertex_cache_miss_count",
        .desc = "Mali-4xx FP: Number of times a requested vertex was not found in the cache (Number of vertex cache misses).",
        .group_id = lima_fragment_processor_group,
        .event = 0x31,
    },
    [lima_pp_varying_cache_hit_count] = {
        .name = "lima_pp_varying_cache_hit_count",
        .desc = "Mali-4xx FP: Number of times a requested varying was found in the cache (Number of varying cache hits).",
        .group_id = lima_fragment_processor_group,
        .event = 0x32,
    },
    [lima_pp_varying_cache_miss_count] = {
        .name = "lima_pp_varying_cache_miss_count",
        .desc = "Mali-4xx FP: Number of times a requested varying was not found in the cache (Number of varying cache misses).",
        .group_id = lima_fragment_processor_group,
        .event = 0x33,
    },
    [lima_pp_varying_cache_conflict_miss_count] = {
        .name = "lima_pp_varying_cache_conflict_miss_count",
        .desc = "Mali-4xx FP: Number of times a requested varying was not in the cache and its value, retrieved from memory, must overwrite an older cache entry. This happens when an access pattern cannot be serviced by the cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x34,
    },
    [lima_pp_texture_cache_hit_count] = {
        .name = "lima_pp_texture_cache_hit_count",
        .desc = "Mali-4xx FP: Number of times a requested texel was found in the texture cache (Number of texture cache hits).",
        .group_id = lima_fragment_processor_group,
        .event = 0x35,
    },
    [lima_pp_texture_cache_miss_count] = {
        .name = "lima_pp_texture_cache_miss_count",
        .desc = "Mali-4xx FP: Number of times a requested texel was not found in the texture cache (Number of texture cache misses).",
        .group_id = lima_fragment_processor_group,
        .event = 0x36,
    },
    [lima_pp_texture_cache_conflict_miss_count] = {
        .name = "lima_pp_texture_cache_conflict_miss_count",
        .desc = "Mali-4xx FP: Number of times a requested texel was not in the cache and its value, retrieved from memory, must overwrite an older cache entry. This happens when an access pattern cannot be serviced by the cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x37,
    },
    [lima_pp_compressed_texture_cache_hit_count] = {
        .name = "lima_pp_compressed_texture_cache_hit_count",
        .desc = "Mali-4xx FP: Number of times a requested item was found in the cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x38,
    },
    [lima_pp_compressed_texture_cache_miss_count] = {
        .name = "lima_pp_compressed_texture_cache_miss_count",
        .desc = "Mali-4xx FP: Number of times a requested item was not found in the cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x39,
    },
    [lima_pp_load_store_cache_hit_count] = {
        .name = "lima_pp_load_store_cache_hit_count",
        .desc = "Mali-4xx FP: Number of hits in the load/store cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x3a,
    },
    [lima_pp_load_store_cache_miss_count] = {
        .name = "lima_pp_load_store_cache_miss_count",
        .desc = "Mali-4xx FP: Number of misses in the load/store cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x3b,
    },
    [lima_pp_program_cache_hit_count] = {
        .name = "lima_pp_program_cache_hit_count",
        .desc = "Mali-4xx FP: Number of hits in the program cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x3c,
    },
    [lima_pp_program_cache_miss_count] = {
        .name = "lima_pp_program_cache_miss_count",
        .desc = "Mali-4xx FP: Number of misses in the program cache.",
        .group_id = lima_fragment_processor_group,
        .event = 0x3d,
    },
    [lima_l2_cache_read_transactions_master] = {
        .name = "lima_l2_cache_read_transactions_master",
        .desc = "Mali L2 Cache: Read transactions (Master)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x08,
    },
    [lima_l2_cache_read_transactions_all_slaves] = {
        .name = "lima_l2_cache_read_transactions_all_slaves",
        .desc = "Mali L2 Cache: Read transactions (All slaves)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x10,
    },
    [lima_l2_cache_read_transactions_slave_0] = {
        .name = "lima_l2_cache_read_transactions_slave_0",
        .desc = "Mali L2 Cache: Read transactions (Slave 0)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x20,
    },
    [lima_l2_cache_read_transactions_slave_1] = {
        .name = "lima_l2_cache_read_transactions_slave_1",
        .desc = "Mali L2 Cache: Read transactions (Slave 1)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x30,
    },
    [lima_l2_cache_read_transactions_slave_2] = {
        .name = "lima_l2_cache_read_transactions_slave_2",
        .desc = "Mali L2 Cache: Read transactions (Slave 2)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x40,
    },
    [lima_l2_cache_read_transactions_slave_3] = {
        .name = "lima_l2_cache_read_transactions_slave_3",
        .desc = "Mali L2 Cache: Read transactions (Slave 3)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x50,
    },
    [lima_l2_cache_read_transactions_slave_4] = {
        .name = "lima_l2_cache_read_transactions_slave_4",
        .desc = "Mali L2 Cache: Read transactions (Slave 4)",
        .group_id = lima_l2_group,
        .event = 0x00,
        .event_delta = 0x60,
    },
    [lima_l2_cache_total_clock_cycles] = {
        .name = "lima_l2_cache_total_clock_cycles",
        .desc = "Mali L2 Cache: Total clock cycles",
        .group_id = lima_l2_group,
        .event = 0x01,
    },
    [lima_l2_cache_write_transactions_master] = {
        .name = "lima_l2_cache_write_transactions_master",
        .desc = "Mali L2 Cache: Write transactions (Master)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x08,
    },
    [lima_l2_cache_write_transactions_all_slaves] = {
        .name = "lima_l2_cache_write_transactions_all_slaves",
        .desc = "Mali L2 Cache: Write transactions (All slaves)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x10,
    },
    [lima_l2_cache_write_transactions_slave_0] = {
        .name = "lima_l2_cache_write_transactions_slave_0",
        .desc = "Mali L2 Cache: Write transactions (Slave 0)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x20,
    },
    [lima_l2_cache_write_transactions_slave_1] = {
        .name = "lima_l2_cache_write_transactions_slave_1",
        .desc = "Mali L2 Cache: Write transactions (Slave 1)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x30,
    },
    [lima_l2_cache_write_transactions_slave_2] = {
        .name = "lima_l2_cache_write_transactions_slave_2",
        .desc = "Mali L2 Cache: Write transactions (Slave 2)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x40,
    },
    [lima_l2_cache_write_transactions_slave_3] = {
        .name = "lima_l2_cache_write_transactions_slave_3",
        .desc = "Mali L2 Cache: Write transactions (Slave 3)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x50,
    },
    [lima_l2_cache_write_transactions_slave_4] = {
        .name = "lima_l2_cache_write_transactions_slave_4",
        .desc = "Mali L2 Cache: Write transactions (Slave 4)",
        .group_id = lima_l2_group,
        .event = 0x01,
        .event_delta = 0x60,
    },
    [lima_l2_cache_active_clock_cycles] = {
        .name = "lima_l2_cache_active_clock_cycles",
        .desc = "Mali L2 Cache: Active clock cycles",
        .group_id = lima_l2_group,
        .event = 0x02,
    },
    [lima_l2_cache_words_read_master] = {
        .name = "lima_l2_cache_words_read_master",
        .desc = "Mali L2 Cache: Words read (Master)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x08,
    },
    [lima_l2_cache_words_read_all_slaves] = {
        .name = "lima_l2_cache_words_read_all_slaves",
        .desc = "Mali L2 Cache: Words read (All slaves)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x10,
    },
    [lima_l2_cache_words_read_slave_0] = {
        .name = "lima_l2_cache_words_read_slave_0",
        .desc = "Mali L2 Cache: Words read (Slave 0)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x20,
    },
    [lima_l2_cache_words_read_slave_1] = {
        .name = "lima_l2_cache_words_read_slave_1",
        .desc = "Mali L2 Cache: Words read (Slave 1)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x30,
    },
    [lima_l2_cache_words_read_slave_2] = {
        .name = "lima_l2_cache_words_read_slave_2",
        .desc = "Mali L2 Cache: Words read (Slave 2)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x40,
    },
    [lima_l2_cache_words_read_slave_3] = {
        .name = "lima_l2_cache_words_read_slave_3",
        .desc = "Mali L2 Cache: Words read (Slave 3)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x50,
    },
    [lima_l2_cache_words_read_slave_4] = {
        .name = "lima_l2_cache_words_read_slave_4",
        .desc = "Mali L2 Cache: Words read (Slave 4)",
        .group_id = lima_l2_group,
        .event = 0x02,
        .event_delta = 0x60,
    },
    [lima_l2_cache_words_written_master] = {
        .name = "lima_l2_cache_words_written_master",
        .desc = "Mali L2 Cache: Words written (Master)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x08,
    },
    [lima_l2_cache_words_written_all_slaves] = {
        .name = "lima_l2_cache_words_written_all_slaves",
        .desc = "Mali L2 Cache: Words written (All slaves)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x10,
    },
    [lima_l2_cache_words_written_slave_0] = {
        .name = "lima_l2_cache_words_written_slave_0",
        .desc = "Mali L2 Cache: Words written (Slave 0)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x20,
    },
    [lima_l2_cache_words_written_slave_1] = {
        .name = "lima_l2_cache_words_written_slave_1",
        .desc = "Mali L2 Cache: Words written (Slave 1)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x30,
    },
    [lima_l2_cache_words_written_slave_2] = {
        .name = "lima_l2_cache_words_written_slave_2",
        .desc = "Mali L2 Cache: Words written (Slave 2)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x40,
    },
    [lima_l2_cache_words_written_slave_3] = {
        .name = "lima_l2_cache_words_written_slave_3",
        .desc = "Mali L2 Cache: Words written (Slave 3)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x50,
    },
    [lima_l2_cache_words_written_slave_4] = {
        .name = "lima_l2_cache_words_written_slave_4",
        .desc = "Mali L2 Cache: Words written (Slave 4)",
        .group_id = lima_l2_group,
        .event = 0x03,
        .event_delta = 0x60,
    },
    [lima_l2_cache_read_hits] = {
        .name = "lima_l2_cache_read_hits",
        .desc = "Mali L2 Cache: Read hits",
        .group_id = lima_l2_group,
        .event = 0x04,
    },
    [lima_l2_cache_read_misses] = {
        .name = "lima_l2_cache_read_misses",
        .desc = "Mali L2 Cache: Read misses",
        .group_id = lima_l2_group,
        .event = 0x05,
    },
    [lima_l2_cache_write_invalidates] = {
        .name = "lima_l2_cache_write_invalidates",
        .desc = "Mali L2 Cache: Write invalidates",
        .group_id = lima_l2_group,
        .event = 0x06,
    },
    [lima_l2_cache_read_invalidates] = {
        .name = "lima_l2_cache_read_invalidates",
        .desc = "Mali L2 Cache: Read invalidates",
        .group_id = lima_l2_group,
        .event = 0x07,
    },
    [lima_l2_cache_cacheable_read_transactions] = {
        .name = "lima_l2_cache_cacheable_read_transactions",
        .desc = "Mali L2 Cache: Cacheable read transactions",
        .group_id = lima_l2_group,
        .event = 0x08,
    },
    [lima_l2_cache_1_read_transactions_master] = {
        .name = "lima_l2_cache_1_read_transactions_master",
        .desc = "Mali L2 Cache 1: Read transactions (Master)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x08,
    },
    [lima_l2_cache_1_read_transactions_all_slaves] = {
        .name = "lima_l2_cache_1_read_transactions_all_slaves",
        .desc = "Mali L2 Cache 1: Read transactions (All slaves)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x10,
    },
    [lima_l2_cache_1_read_transactions_slave_0] = {
        .name = "lima_l2_cache_1_read_transactions_slave_0",
        .desc = "Mali L2 Cache 1: Read transactions (Slave 0)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x20,
    },
    [lima_l2_cache_1_read_transactions_slave_1] = {
        .name = "lima_l2_cache_1_read_transactions_slave_1",
        .desc = "Mali L2 Cache 1: Read transactions (Slave 1)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x30,
    },
    [lima_l2_cache_1_read_transactions_slave_2] = {
        .name = "lima_l2_cache_1_read_transactions_slave_2",
        .desc = "Mali L2 Cache 1: Read transactions (Slave 2)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x40,
    },
    [lima_l2_cache_1_read_transactions_slave_3] = {
        .name = "lima_l2_cache_1_read_transactions_slave_3",
        .desc = "Mali L2 Cache 1: Read transactions (Slave 3)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x50,
    },
    [lima_l2_cache_1_read_transactions_slave_4] = {
        .name = "lima_l2_cache_1_read_transactions_slave_4",
        .desc = "Mali L2 Cache 1: Read transactions (Slave 4)",
        .group_id = lima_l2_1_group,
        .event = 0x00,
        .event_delta = 0x60,
    },
    [lima_l2_cache_1_total_clock_cycles] = {
        .name = "lima_l2_cache_1_total_clock_cycles",
        .desc = "Mali L2 Cache 1: Total clock cycles",
        .group_id = lima_l2_1_group,
        .event = 0x01,
    },
    [lima_l2_cache_1_write_transactions_master] = {
        .name = "lima_l2_cache_1_write_transactions_master",
        .desc = "Mali L2 Cache 1: Write transactions (Master)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x08,
    },
    [lima_l2_cache_1_write_transactions_all_slaves] = {
        .name = "lima_l2_cache_1_write_transactions_all_slaves",
        .desc = "Mali L2 Cache 1: Write transactions (All slaves)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x10,
    },
    [lima_l2_cache_1_write_transactions_slave_0] = {
        .name = "lima_l2_cache_1_write_transactions_slave_0",
        .desc = "Mali L2 Cache 1: Write transactions (Slave 0)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x20,
    },
    [lima_l2_cache_1_write_transactions_slave_1] = {
        .name = "lima_l2_cache_1_write_transactions_slave_1",
        .desc = "Mali L2 Cache 1: Write transactions (Slave 1)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x30,
    },
    [lima_l2_cache_1_write_transactions_slave_2] = {
        .name = "lima_l2_cache_1_write_transactions_slave_2",
        .desc = "Mali L2 Cache 1: Write transactions (Slave 2)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x40,
    },
    [lima_l2_cache_1_write_transactions_slave_3] = {
        .name = "lima_l2_cache_1_write_transactions_slave_3",
        .desc = "Mali L2 Cache 1: Write transactions (Slave 3)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x50,
    },
    [lima_l2_cache_1_write_transactions_slave_4] = {
        .name = "lima_l2_cache_1_write_transactions_slave_4",
        .desc = "Mali L2 Cache 1: Write transactions (Slave 4)",
        .group_id = lima_l2_1_group,
        .event = 0x01,
        .event_delta = 0x60,
    },
    [lima_l2_cache_1_active_clock_cycles] = {
        .name = "lima_l2_cache_1_active_clock_cycles",
        .desc = "Mali L2 Cache 1: Active clock cycles",
        .group_id = lima_l2_1_group,
        .event = 0x02,
    },
    [lima_l2_cache_1_words_read_master] = {
        .name = "lima_l2_cache_1_words_read_master",
        .desc = "Mali L2 Cache 1: Words read (Master)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x08,
    },
    [lima_l2_cache_1_words_read_all_slaves] = {
        .name = "lima_l2_cache_1_words_read_all_slaves",
        .desc = "Mali L2 Cache 1: Words read (All slaves)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x10,
    },
    [lima_l2_cache_1_words_read_slave_0] = {
        .name = "lima_l2_cache_1_words_read_slave_0",
        .desc = "Mali L2 Cache 1: Words read (Slave 0)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x20,
    },
    [lima_l2_cache_1_words_read_slave_1] = {
        .name = "lima_l2_cache_1_words_read_slave_1",
        .desc = "Mali L2 Cache 1: Words read (Slave 1)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x30,
    },
    [lima_l2_cache_1_words_read_slave_2] = {
        .name = "lima_l2_cache_1_words_read_slave_2",
        .desc = "Mali L2 Cache 1: Words read (Slave 2)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x40,
    },
    [lima_l2_cache_1_words_read_slave_3] = {
        .name = "lima_l2_cache_1_words_read_slave_3",
        .desc = "Mali L2 Cache 1: Words read (Slave 3)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x50,
    },
    [lima_l2_cache_1_words_read_slave_4] = {
        .name = "lima_l2_cache_1_words_read_slave_4",
        .desc = "Mali L2 Cache 1: Words read (Slave 4)",
        .group_id = lima_l2_1_group,
        .event = 0x02,
        .event_delta = 0x60,
    },
    [lima_l2_cache_1_words_written_master] = {
        .name = "lima_l2_cache_1_words_written_master",
        .desc = "Mali L2 Cache 1: Words written (Master)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x08,
    },
    [lima_l2_cache_1_words_written_all_slaves] = {
        .name = "lima_l2_cache_1_words_written_all_slaves",
        .desc = "Mali L2 Cache 1: Words written (All slaves)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x10,
    },
    [lima_l2_cache_1_words_written_slave_0] = {
        .name = "lima_l2_cache_1_words_written_slave_0",
        .desc = "Mali L2 Cache 1: Words written (Slave 0)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x20,
    },
    [lima_l2_cache_1_words_written_slave_1] = {
        .name = "lima_l2_cache_1_words_written_slave_1",
        .desc = "Mali L2 Cache 1: Words written (Slave 1)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x30,
    },
    [lima_l2_cache_1_words_written_slave_2] = {
        .name = "lima_l2_cache_1_words_written_slave_2",
        .desc = "Mali L2 Cache 1: Words written (Slave 2)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x40,
    },
    [lima_l2_cache_1_words_written_slave_3] = {
        .name = "lima_l2_cache_1_words_written_slave_3",
        .desc = "Mali L2 Cache 1: Words written (Slave 3)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x50,
    },
    [lima_l2_cache_1_words_written_slave_4] = {
        .name = "lima_l2_cache_1_words_written_slave_4",
        .desc = "Mali L2 Cache 1: Words written (Slave 4)",
        .group_id = lima_l2_1_group,
        .event = 0x03,
        .event_delta = 0x60,
    },
    [lima_l2_cache_1_read_hits] = {
        .name = "lima_l2_cache_1_read_hits",
        .desc = "Mali L2 Cache 1: Read hits",
        .group_id = lima_l2_1_group,
        .event = 0x04,
    },
    [lima_l2_cache_1_read_misses] = {
        .name = "lima_l2_cache_1_read_misses",
        .desc = "Mali L2 Cache 1: Read misses",
        .group_id = lima_l2_1_group,
        .event = 0x05,
    },
    [lima_l2_cache_1_write_invalidates] = {
        .name = "lima_l2_cache_1_write_invalidates",
        .desc = "Mali L2 Cache 1: Write invalidates",
        .group_id = lima_l2_1_group,
        .event = 0x06,
    },
    [lima_l2_cache_1_read_invalidates] = {
        .name = "lima_l2_cache_1_read_invalidates",
        .desc = "Mali L2 Cache 1: Read invalidates",
        .group_id = lima_l2_1_group,
        .event = 0x07,
    },
    [lima_l2_cache_1_cacheable_read_transactions] = {
        .name = "lima_l2_cache_1_cacheable_read_transactions",
        .desc = "Mali L2 Cache 1: Cacheable read transactions",
        .group_id = lima_l2_1_group,
        .event = 0x08,
    },
    [lima_l2_cache_2_read_transactions_master] = {
        .name = "lima_l2_cache_2_read_transactions_master",
        .desc = "Mali L2 Cache 2: Read transactions (Master)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x08,
    },
    [lima_l2_cache_2_read_transactions_all_slaves] = {
        .name = "lima_l2_cache_2_read_transactions_all_slaves",
        .desc = "Mali L2 Cache 2: Read transactions (All slaves)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x10,
    },
    [lima_l2_cache_2_read_transactions_slave_0] = {
        .name = "lima_l2_cache_2_read_transactions_slave_0",
        .desc = "Mali L2 Cache 2: Read transactions (Slave 0)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x20,
    },
    [lima_l2_cache_2_read_transactions_slave_1] = {
        .name = "lima_l2_cache_2_read_transactions_slave_1",
        .desc = "Mali L2 Cache 2: Read transactions (Slave 1)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x30,
    },
    [lima_l2_cache_2_read_transactions_slave_2] = {
        .name = "lima_l2_cache_2_read_transactions_slave_2",
        .desc = "Mali L2 Cache 2: Read transactions (Slave 2)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x40,
    },
    [lima_l2_cache_2_read_transactions_slave_3] = {
        .name = "lima_l2_cache_2_read_transactions_slave_3",
        .desc = "Mali L2 Cache 2: Read transactions (Slave 3)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x50,
    },
    [lima_l2_cache_2_read_transactions_slave_4] = {
        .name = "lima_l2_cache_2_read_transactions_slave_4",
        .desc = "Mali L2 Cache 2: Read transactions (Slave 4)",
        .group_id = lima_l2_2_group,
        .event = 0x00,
        .event_delta = 0x60,
    },
    [lima_l2_cache_2_total_clock_cycles] = {
        .name = "lima_l2_cache_2_total_clock_cycles",
        .desc = "Mali L2 Cache 2: Total clock cycles",
        .group_id = lima_l2_2_group,
        .event = 0x01,
    },
    [lima_l2_cache_2_write_transactions_master] = {
        .name = "lima_l2_cache_2_write_transactions_master",
        .desc = "Mali L2 Cache 2: Write transactions (Master)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x08,
    },
    [lima_l2_cache_2_write_transactions_all_slaves] = {
        .name = "lima_l2_cache_2_write_transactions_all_slaves",
        .desc = "Mali L2 Cache 2: Write transactions (All slaves)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x10,
    },
    [lima_l2_cache_2_write_transactions_slave_0] = {
        .name = "lima_l2_cache_2_write_transactions_slave_0",
        .desc = "Mali L2 Cache 2: Write transactions (Slave 0)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x20,
    },
    [lima_l2_cache_2_write_transactions_slave_1] = {
        .name = "lima_l2_cache_2_write_transactions_slave_1",
        .desc = "Mali L2 Cache 2: Write transactions (Slave 1)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x30,
    },
    [lima_l2_cache_2_write_transactions_slave_2] = {
        .name = "lima_l2_cache_2_write_transactions_slave_2",
        .desc = "Mali L2 Cache 2: Write transactions (Slave 2)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x40,
    },
    [lima_l2_cache_2_write_transactions_slave_3] = {
        .name = "lima_l2_cache_2_write_transactions_slave_3",
        .desc = "Mali L2 Cache 2: Write transactions (Slave 3)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x50,
    },
    [lima_l2_cache_2_write_transactions_slave_4] = {
        .name = "lima_l2_cache_2_write_transactions_slave_4",
        .desc = "Mali L2 Cache 2: Write transactions (Slave 4)",
        .group_id = lima_l2_2_group,
        .event = 0x01,
        .event_delta = 0x60,
    },
    [lima_l2_cache_2_active_clock_cycles] = {
        .name = "lima_l2_cache_2_active_clock_cycles",
        .desc = "Mali L2 Cache 2: Active clock cycles",
        .group_id = lima_l2_2_group,
        .event = 0x02,
    },
    [lima_l2_cache_2_words_read_master] = {
        .name = "lima_l2_cache_2_words_read_master",
        .desc = "Mali L2 Cache 2: Words read (Master)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x08,
    },
    [lima_l2_cache_2_words_read_all_slaves] = {
        .name = "lima_l2_cache_2_words_read_all_slaves",
        .desc = "Mali L2 Cache 2: Words read (All slaves)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x10,
    },
    [lima_l2_cache_2_words_read_slave_0] = {
        .name = "lima_l2_cache_2_words_read_slave_0",
        .desc = "Mali L2 Cache 2: Words read (Slave 0)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x20,
    },
    [lima_l2_cache_2_words_read_slave_1] = {
        .name = "lima_l2_cache_2_words_read_slave_1",
        .desc = "Mali L2 Cache 2: Words read (Slave 1)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x30,
    },
    [lima_l2_cache_2_words_read_slave_2] = {
        .name = "lima_l2_cache_2_words_read_slave_2",
        .desc = "Mali L2 Cache 2: Words read (Slave 2)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x40,
    },
    [lima_l2_cache_2_words_read_slave_3] = {
        .name = "lima_l2_cache_2_words_read_slave_3",
        .desc = "Mali L2 Cache 2: Words read (Slave 3)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x50,
    },
    [lima_l2_cache_2_words_read_slave_4] = {
        .name = "lima_l2_cache_2_words_read_slave_4",
        .desc = "Mali L2 Cache 2: Words read (Slave 4)",
        .group_id = lima_l2_2_group,
        .event = 0x02,
        .event_delta = 0x60,
    },
    [lima_l2_cache_2_words_written_master] = {
        .name = "lima_l2_cache_2_words_written_master",
        .desc = "Mali L2 Cache 2: Words written (Master)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x08,
    },
    [lima_l2_cache_2_words_written_all_slaves] = {
        .name = "lima_l2_cache_2_words_written_all_slaves",
        .desc = "Mali L2 Cache 2: Words written (All slaves)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x10,
    },
    [lima_l2_cache_2_words_written_slave_0] = {
        .name = "lima_l2_cache_2_words_written_slave_0",
        .desc = "Mali L2 Cache 2: Words written (Slave 0)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x20,
    },
    [lima_l2_cache_2_words_written_slave_1] = {
        .name = "lima_l2_cache_2_words_written_slave_1",
        .desc = "Mali L2 Cache 2: Words written (Slave 1)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x30,
    },
    [lima_l2_cache_2_words_written_slave_2] = {
        .name = "lima_l2_cache_2_words_written_slave_2",
        .desc = "Mali L2 Cache 2: Words written (Slave 2)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x40,
    },
    [lima_l2_cache_2_words_written_slave_3] = {
        .name = "lima_l2_cache_2_words_written_slave_3",
        .desc = "Mali L2 Cache 2: Words written (Slave 3)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x50,
    },
    [lima_l2_cache_2_words_written_slave_4] = {
        .name = "lima_l2_cache_2_words_written_slave_4",
        .desc = "Mali L2 Cache 2: Words written (Slave 4)",
        .group_id = lima_l2_2_group,
        .event = 0x03,
        .event_delta = 0x60,
    },
    [lima_l2_cache_2_read_hits] = {
        .name = "lima_l2_cache_2_read_hits",
        .desc = "Mali L2 Cache 2: Read hits",
        .group_id = lima_l2_2_group,
        .event = 0x04,
    },
    [lima_l2_cache_2_read_misses] = {
        .name = "lima_l2_cache_2_read_misses",
        .desc = "Mali L2 Cache 2: Read misses",
        .group_id = lima_l2_2_group,
        .event = 0x05,
    },
    [lima_l2_cache_2_write_invalidates] = {
        .name = "lima_l2_cache_2_write_invalidates",
        .desc = "Mali L2 Cache 2: Write invalidates",
        .group_id = lima_l2_2_group,
        .event = 0x06,
    },
    [lima_l2_cache_2_read_invalidates] = {
        .name = "lima_l2_cache_2_read_invalidates",
        .desc = "Mali L2 Cache 2: Read invalidates",
        .group_id = lima_l2_2_group,
        .event = 0x07,
    },
    [lima_l2_cache_2_cacheable_read_transactions] = {
        .name = "lima_l2_cache_2_cacheable_read_transactions",
        .desc = "Mali L2 Cache 2: Cacheable read transactions",
        .group_id = lima_l2_2_group,
        .event = 0x08,
    },
};
