[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
    "/deqp/mustpass/gles2-main.txt",
    "/deqp/mustpass/gles3-main.txt",
    "/deqp/mustpass/gles31-main.txt",
    "/deqp/mustpass/gl46-main.txt",
]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0
tests_per_group = 1000
renderer_check = "zink.*NVK"

[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
timeout = 180.0
  [piglit.env]
  PIGLIT_NO_WINDOW = "1"
  PIGLIT_PLATFORM = "gbm"
  WAFFLE_PLATFORM = "gbm"

[[piglit]]
piglit_folder = "/piglit"
profile = "cl"
process_isolation = true
  [piglit.env]
  RUSTICL_ENABLE = "zink"
  # Disable validation on piglit.  We end up with use-after-frees from
  # piglit_report() -> exit() having freed validation layer state, with a
  # st_glFlush() -> tc_batch_execute() -> zink_set_vertex_buffers ->
  # vulkan_layer_chassis::CmdPipelineBarrier2() (etc.) happening after that
  # somehow.
  ZINK_DEBUG = ""
