#######################################################################
# SConscript for vkwsi winsys


Import('*')

env = env.Clone()

env.Append(CPPPATH = [
    '#/src/gallium/include',
    '#/src/gallium/auxiliary',
])

ws_vkapi = env.ConvenienceLibrary(
    target = 'ws_vkapi',
    source = env.ParseSourceList('Makefile.sources', 'C_SOURCES'),
)
env.Alias('ws_vkapi', ws_vkapi)
Export('ws_vkapi')
