.virgl-test:
  extends:
    - .test-gl
    - .virgl-rules
  variables:
    GALLIUM_DRIVER: "virgl"
    CROSVM_GALLIUM_DRIVER: "llvmpipe"
    CROSVM_GPU_ARGS: "gles=false,backend=virglrenderer,egl=true,surfaceless=true"
    GALLIVM_PERF: "nopt,no_quad_lod"

virgl-on-gl:
  variables:
    DEQP_SUITE: virgl-gl
    GPU_VERSION: virgl-gl
    DEQP_EXPECTED_RENDERER: llvmpipe  # For renderer check, remove once it moves into deqp-runner
    DEQP_VER: gles2 # For renderer check, remove once it moves into deqp-runner
    LIBGL_ALWAYS_SOFTWARE: "true" # For renderer check, remove once it moves into deqp-runner
    GALLIUM_DRIVER: "llvmpipe" # For renderer check, remove once it moves into deqp-runner
  parallel: 3
  tags:
    - kvm
  extends:
    - .deqp-test
    - .virgl-test

virgl-on-gles:
  variables:
    VIRGL_HOST_API: GLES
    DEQP_SUITE: virgl-gles
    GPU_VERSION: virgl-gles
    CROSVM_GPU_ARGS: "gles=true,backend=virglrenderer,egl=true,surfaceless=true"
  extends:
    - virgl-on-gl

virgl-traces:
  extends:
    - .virgl-test
    - .piglit-traces-test
  variables:
    EGL_PLATFORM: "surfaceless"
    PIGLIT_REPLAY_DESCRIPTION_FILE: "${CI_PROJECT_DIR}/install/traces-virgl.yml"
    PIGLIT_REPLAY_DEVICE_NAME: "gl-virgl"
    PIGLIT_RESULTS: "virgl-replay"
    LD_LIBRARY_PATH: "${CI_PROJECT_DIR}/install/lib/"     # For Crosvm
  tags:
    - kvm
  script:
    - install/crosvm-runner.sh install/piglit/run.sh

